name: Pull Request Action

on:
  pull_request:
    types: [closed, opened]
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: create-pr
        run: echo Hello world!